export const rating=[
    {
        name:"ArtDesRadwegs",
        choises:[
            {
                title:"Straße Tempo 30",
                werte:[7,8,8]
            },
            {
                title:"Straße Tempo 50",
                werte:[5,8,8]
            },
            {
                title:"Straße Tempo 60-80",
                werte:[3,7,8]
            },
            {
                title:"Straße Tempo 100",
                werte:[1,6,6]
            },
            {
                title:"Radweg",
                werte:[10,10,8]
            },
            {
                title:"Schutzstreifen",
                werte:[6,8,8]
            },
            {
                title:"Radfahrstreifen",
                werte:[8,9,8]
            },
            {
                title:"geschützter Radfahrstreifen",
                werte:[10,10,8]
            },
            {
                title:"Fahrradstraße",
                werte:[10,10,10]
            },
            {
                title:"Fahrrad- und Fußweg",
                werte:[9,9,10]
            }
        ]
    },
    {
        name:"weiteDesWegsProRichtung",
        choises:[
            {
                title:"<50cm",
                werte:[-5,-5,-5]
            },
            {
                title:"50cm-1m",
                werte:[-2,-3,-3]
            },
            {
                title:">1m",
                werte:[0,0,0]
            }
        ]
    },
    {
        name:"Belag",
        choises:[
            {
                title:"Erde",
                werte:[-3,-8,0]
            },
            {
                title:"Kopfsteinpflaster",
                werte:[-5,-7,0]
            },
            {
                title:"Sandweg",
                werte:[0,-3,0]
            },
            {
                title:"kleine Ziegelsteine",
                werte:[-1,-3,0]
            },
            {
                title:"große Radwegsteine",
                werte:[0,-2,0]
            },
            {
                title:"rauer Asphalt",
                werte:[-1,-2,0]
            },
            {
                title:"aslphalt",
                werte:[0,-1,0]
            },
            {
                title:"fahrradAsphalt",
                werte:[0,0,0]
            }
        ]
    },
    {
        name:"Belagszustand",
        choises:[
            {
                title:"unzähligeBeschädigung",
                werte:[-3,-8,0]
            },
            {
                title:"mehrereAuf500Metern",
                werte:[-3,-6,0]
            },
            {
                title:"alle500Meter",
                werte:[-3,-5,0]
            },
            {
                title:"alleKilometer",
                werte:[-2,-3,0]
            },
            {
                title:"vereinzelnt",
                werte:[-3,-1,0]
            },
            {
                title:"keine",
                werte:[0,0,0]
            },
        ]
    },
    {
        name:"VerkehrsaufkommenNebenDemRadweg",
        choises:[
            {
                title:"ImmerVoll",
                werte:[0,0,-7]
            },
            {
                title:"ImmerAutos",
                werte:[0,0,-7]
            },
            {
                title:"HälfteAutos",
                werte:[0,0,-5]
            },
            {
                title:"wenigAutos",
                werte:[0,0,-3]
            },
            {
                title:"kaumAutos",
                werte:[0,0,-2]
            },
            {
                title:"keineAutos",
                werte:[0,0,0]
            }
        ]
    },
    {
        name:"VerkehrsaufkommenAufDemRadweg",
        choises:[
            {
                title:"ImmerVoll",
                werte:[-7,-7,-7]
            },
            {
                title:"ImmerAutos",
                werte:[-7,-6,-7]
            },
            {
                title:"HälfteAutos",
                werte:[-5,-5,-5]
            },
            {
                title:"wenigAutos",
                werte:[-3,-2,-3]
            },
            {
                title:"kaumAutos",
                werte:[-1,0,-2]
            },
            {
                title:"keineAutos",
                werte:[0,0,0]
            }
        ]
    }
]